name: sphincs_plus_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  sphincs_plus:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
